### ISSUE TITLE
implement commit signing verification across the stack

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/coding#13]
- started in this commit https://github.com/eris-ltd/eris-db.js/commit/e72fd4461ad9590af1c427f9380d1fa25970d545
- include tips to facilitate adjusment to workflow [zr]
- [x] eris-db.js
- [ ] eris-contracts.js
- [ ] eris-keys.js
- [ ] eris-keys
- [ ] eris-cm
- [x] eris-db
- [ ] eris-pm
- [ ] eris-cli
- [ ] toadserver
- [ ] docs.erisindustries.com (maybe?)

**Comment by benjaminbollen** [comment]
on CI I get
https://circleci.com/gh/eris-ltd/eris-db/468
```git verify-commit HEAD
gpg: Signature made Fri 10 Jun 2016 10:21:06 PM UTC using RSA key ID FBEAF215
gpg: Can't check signature: public key not found

git verify-commit HEAD returned exit code 1```

**Comment by benjaminbollen** [comment]
in response to above I pieced together some shell magic from the internets to collect all keys found from a certain point on the history on-ward; import these keys from a selected list of key servers; trust all these keys and verify that every commit is signed by one of those keys.
https://github.com/eris-ltd/eris-db/pull/140

**Comment by compleatang** [comment]
@AFDudley does it make sense to have build_ or deploy_ or test_ jobs check this at the Jenkins level or does it make more sense for it to be a repo maintainers exclusive responsibility (without Jenkins checks)?

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/operations #60](https://github.com/eris-ltd/operations/issues/60) via [**ZenHub**](https://www.zenhub.com/)
