### ISSUE TITLE
[Repo Management] harmonize repo & docker image names

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/coding#19]
@zramsay commented on [Tue Jul 05 2016](https://github.com/eris-ltd/eris-cli/issues/783)

only `eris-cm` matches the repo name & the other images have no consistency between them.
```
eris/keys
eris/erisdb
eris/epm
eris/eris-cm
```

ideas:
```
eris/ekeys
eris/edb
eris/epm
eris/ecm
```
or match repo names identically:
```
eris/eris-keys
eris/eris-db
eris/eris-pm
eris/eris-cm
```

---

@zramsay commented on [Tue Jul 05 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-230501597)

related to & can happen at same time as #782 

---

@zramsay commented on [Tue Jul 05 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-230504526)

+2 for matching repo names. Eventually we'll want to match the username with the GH org name

---

@pietv commented on [Tue Aug 02 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-236908088)

:+1: for `eris-*` over `e*` everything if there's a reason not to drop the `eris-` from the image name (`eris/eris-*` is duplicated).

---

@AFDudley commented on [Thu Aug 18 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-240781510)

we should remove the `eris-`

---

@compleatang commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-241372260)

I agree with Rick here. Both the repos and the docker image names should be changed imv.

Repos:

```
github.com/eris-ltd/eris-cli -> github.com/eris-ltd/cli
github.com/eris-ltd/eris-compilers -> github.com/eris-ltd/compilers
etc.
```

Docker Images:

```
quay.io/eris/epm -> quay.io/eris/pm
quay.io/eris/eris-cm -> quay.io/eris/cm
quay.io/eris/erisdb -> quay.io/eris/db
etc.
```

---

@benjaminbollen commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-241392050)

I want to offer the suggestion of using full names everywhere to be considered too
```
github.com/eris-ltd/commandline
github.com/eris-ltd/database
github.com/eris-ltd/chainmanager
github.com/eris-ltd/packagemanager
github.com/eris-ltd/keys
github.com/eris-ltd/compilers
```

for quay.io images 
```
quay.io/eris/packagemanager
quay.io/eris/chainmanager
quay.io/eris/database
quay.io/eris/keys
quay.io/eris/compilers
```

---

@pietv commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-241400002)

:+1: for renaming `cm` and `pm` to `github.com/eris-ltd/chainmanager` or `github.com/eris-ltd/packagemanager`

there's no point in renaming `cli` or `db` — the abbreviations are quite clear as they are now.

---

@compleatang commented on [Mon Aug 22 2016](https://github.com/eris-ltd/eris-cli/issues/783#issuecomment-241423061)

moving to coding

**Comment by benjaminbollen** [comment]
I'm good to follow @compleatang on this.

**Comment by compleatang** [comment]
To summarize the decision point, we have four options to harmonize our names:

**1. eAbbrev notation**

```
quay.io/eris/edb
github.com/eris-ltd/edb
```

**2. eris-Abbrev notation**

```
quay.io/eris/eris-db
github.com/eris-ltd/eris-db
```

**3. Abbrev only notation**

```
quay.io/eris/db
github.com/eris-ltd/db
```

**4. Full name notation**

```
quay.io/eris/database
github.com/eris-ltd/database
```

@eris-ltd/team-platform Please make your votes known below so that we can finalize this.

**Comment by compleatang** [comment]
I vote for Number 3.

**Comment by pietv** [comment]
3

**Comment by benjaminbollen** [comment]
I'll explicitly cast my vote as per Casey, 3

**Comment by silasdavis** [comment]
Ok it's hard coming it now and not be contrary. But yeah, 3.

Definitely not 4, too explicit.

**Comment by VoR0220** [comment]
I vote for 1

**Comment by AFDudley** [comment]
The problem with 3 is collisions. otherwise, I like it. People use code-names and silly hipster names to avoid collisions... 
>ubuntu@ip-172-31-61-166:~$ keys
>No command 'keys' found, did you mean:
> Command 'key' from package 'donkey' (universe)
> Command 'keyd' from package 'onak' (universe)
>keys: command not found

>ubuntu@ip-172-31-61-166:~$ db
>db: command not found

>ubuntu@ip-172-31-61-166:~$ pm
>The program 'pm' is currently not installed. You can install it by typing:
>sudo apt-get install powerman

>ubuntu@ip-172-31-61-166:~$ cm
>The program 'cm' is currently not installed. You can install it by typing:
>sudo apt-get install config-manager

**Comment by compleatang** [comment]
OK. voting is closed. it looks like we all agree on `3` but with the caveat that we need to be aware of any potential name conflicts. since we 50% distribute our software via docker images then is not a huge concern as docker uses explicit namespacing in its images. the binary that we distribute ( `eris` ) can be appropriately named. Down the road if we distribute db as a binary we'll cross that bridge at that time. 

Let's begin to action the repository renaming on all relevant docker images and repositories.
