### ISSUE TITLE
[Documentation] Setting up a dev environment for eris-cli

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/coding#4]
from: https://github.com/eris-ltd/eng.erisindustries.com/issues/6

**Comment by zramsay** [comment]
use the nice docker way rather than the hacky scripts

**Comment by compleatang** [comment]
Issue moved to [eris-ltd/eris-cli #1004](https://github.com/eris-ltd/eris-cli/issues/1004) via [**ZenHub**](https://www.zenhub.com/)
