### ISSUE TITLE
Document github branching/merging/versioning/tagging in wiki

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/coding#5]

**Comment by j-h-scheufen** [comment]
We're already following an almost identical flow as described in this post that has become a base go-to for git product lifecycle: http://nvie.com/posts/a-successful-git-branching-model/
I'd like to propose to take this as a basis and add a few lines around the Github specifics, e.g. pushing branches to origin and working with pull requests

**Comment by compleatang** [comment]
++

**Comment by compleatang** [comment]
edit away folks! https://github.com/eris-ltd/coding/wiki/How-The-Marmots-Git
